/* config.h. Generated by CMake for SDFormat. */

/* Protocol version */
#define SDF_PROTOCOL_VERSION "1.6"
/* \deprecated SDF_VERSION is deprecated. Please
 * use SDF_PROTOCOL_VERSION or SDF_PKG_VERSION
 *
 * SDF_VERSION is here to keep backwards compatibility. It was used
 * when the package version and protocol version were the same
 */
#define SDF_VERSION "1.6"

/* Package version number */
#define SDF_MAJOR_VERSION 6
#define SDF_MINOR_VERSION 0
#define SDF_PATCH_VERSION 0

#define SDF_PKG_VERSION "6.0"
#define SDF_VERSION_FULL "6.0.0"
#define SDF_VERSION_NAME 

#define SDF_VERSION_HEADER "Simulation Description Format (SDF), version 1.6\nCopyright (C) 2014 Open Source Robotics Foundation.\nReleased under the Apache 2 License.\nhttp://gazebosim.org/sdf\n\n"

#define BUILD_TYPE_PROFILE 1
#define BUILD_TYPE_DEBUG 1
#define BUILD_TYPE_RELEASE 1
/* #undef HAVE_URDFDOM */
/* #undef USE_INTERNAL_URDF */

#define SDF_SHARE_PATH "external/sdformat/sdf/1.6/"
#define SDF_VERSION_PATH "external/sdformat/sdf/1.6/sdformat/"
