// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: drake/common/proto/matlab_rpc.proto

#ifndef PROTOBUF_drake_2fcommon_2fproto_2fmatlab_5frpc_2eproto__INCLUDED
#define PROTOBUF_drake_2fcommon_2fproto_2fmatlab_5frpc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_drake_2fcommon_2fproto_2fmatlab_5frpc_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsMatlabArrayImpl();
void InitDefaultsMatlabArray();
void InitDefaultsMatlabRPCImpl();
void InitDefaultsMatlabRPC();
inline void InitDefaults() {
  InitDefaultsMatlabArray();
  InitDefaultsMatlabRPC();
}
}  // namespace protobuf_drake_2fcommon_2fproto_2fmatlab_5frpc_2eproto
namespace drake {
namespace common {
class MatlabArray;
class MatlabArrayDefaultTypeInternal;
extern MatlabArrayDefaultTypeInternal _MatlabArray_default_instance_;
class MatlabRPC;
class MatlabRPCDefaultTypeInternal;
extern MatlabRPCDefaultTypeInternal _MatlabRPC_default_instance_;
}  // namespace common
}  // namespace drake
namespace drake {
namespace common {

enum MatlabArray_ArrayType {
  MatlabArray_ArrayType_REMOTE_VARIABLE_REFERENCE = 0,
  MatlabArray_ArrayType_DOUBLE = 1,
  MatlabArray_ArrayType_CHAR = 2,
  MatlabArray_ArrayType_LOGICAL = 3,
  MatlabArray_ArrayType_INT = 4
};
bool MatlabArray_ArrayType_IsValid(int value);
const MatlabArray_ArrayType MatlabArray_ArrayType_ArrayType_MIN = MatlabArray_ArrayType_REMOTE_VARIABLE_REFERENCE;
const MatlabArray_ArrayType MatlabArray_ArrayType_ArrayType_MAX = MatlabArray_ArrayType_INT;
const int MatlabArray_ArrayType_ArrayType_ARRAYSIZE = MatlabArray_ArrayType_ArrayType_MAX + 1;

const ::google::protobuf::EnumDescriptor* MatlabArray_ArrayType_descriptor();
inline const ::std::string& MatlabArray_ArrayType_Name(MatlabArray_ArrayType value) {
  return ::google::protobuf::internal::NameOfEnum(
    MatlabArray_ArrayType_descriptor(), value);
}
inline bool MatlabArray_ArrayType_Parse(
    const ::std::string& name, MatlabArray_ArrayType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MatlabArray_ArrayType>(
    MatlabArray_ArrayType_descriptor(), name, value);
}
enum MatlabArray_ShapeType {
  MatlabArray_ShapeType_MATRIX = 0,
  MatlabArray_ShapeType_VECTOR = 1,
  MatlabArray_ShapeType_SCALAR = 2
};
bool MatlabArray_ShapeType_IsValid(int value);
const MatlabArray_ShapeType MatlabArray_ShapeType_ShapeType_MIN = MatlabArray_ShapeType_MATRIX;
const MatlabArray_ShapeType MatlabArray_ShapeType_ShapeType_MAX = MatlabArray_ShapeType_SCALAR;
const int MatlabArray_ShapeType_ShapeType_ARRAYSIZE = MatlabArray_ShapeType_ShapeType_MAX + 1;

const ::google::protobuf::EnumDescriptor* MatlabArray_ShapeType_descriptor();
inline const ::std::string& MatlabArray_ShapeType_Name(MatlabArray_ShapeType value) {
  return ::google::protobuf::internal::NameOfEnum(
    MatlabArray_ShapeType_descriptor(), value);
}
inline bool MatlabArray_ShapeType_Parse(
    const ::std::string& name, MatlabArray_ShapeType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MatlabArray_ShapeType>(
    MatlabArray_ShapeType_descriptor(), name, value);
}
// ===================================================================

class MatlabArray : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:drake.common.MatlabArray) */ {
 public:
  MatlabArray();
  virtual ~MatlabArray();

  MatlabArray(const MatlabArray& from);

  inline MatlabArray& operator=(const MatlabArray& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MatlabArray(MatlabArray&& from) noexcept
    : MatlabArray() {
    *this = ::std::move(from);
  }

  inline MatlabArray& operator=(MatlabArray&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MatlabArray& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MatlabArray* internal_default_instance() {
    return reinterpret_cast<const MatlabArray*>(
               &_MatlabArray_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(MatlabArray* other);
  friend void swap(MatlabArray& a, MatlabArray& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MatlabArray* New() const PROTOBUF_FINAL { return New(NULL); }

  MatlabArray* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MatlabArray& from);
  void MergeFrom(const MatlabArray& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MatlabArray* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef MatlabArray_ArrayType ArrayType;
  static const ArrayType REMOTE_VARIABLE_REFERENCE =
    MatlabArray_ArrayType_REMOTE_VARIABLE_REFERENCE;
  static const ArrayType DOUBLE =
    MatlabArray_ArrayType_DOUBLE;
  static const ArrayType CHAR =
    MatlabArray_ArrayType_CHAR;
  static const ArrayType LOGICAL =
    MatlabArray_ArrayType_LOGICAL;
  static const ArrayType INT =
    MatlabArray_ArrayType_INT;
  static inline bool ArrayType_IsValid(int value) {
    return MatlabArray_ArrayType_IsValid(value);
  }
  static const ArrayType ArrayType_MIN =
    MatlabArray_ArrayType_ArrayType_MIN;
  static const ArrayType ArrayType_MAX =
    MatlabArray_ArrayType_ArrayType_MAX;
  static const int ArrayType_ARRAYSIZE =
    MatlabArray_ArrayType_ArrayType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ArrayType_descriptor() {
    return MatlabArray_ArrayType_descriptor();
  }
  static inline const ::std::string& ArrayType_Name(ArrayType value) {
    return MatlabArray_ArrayType_Name(value);
  }
  static inline bool ArrayType_Parse(const ::std::string& name,
      ArrayType* value) {
    return MatlabArray_ArrayType_Parse(name, value);
  }

  typedef MatlabArray_ShapeType ShapeType;
  static const ShapeType MATRIX =
    MatlabArray_ShapeType_MATRIX;
  static const ShapeType VECTOR =
    MatlabArray_ShapeType_VECTOR;
  static const ShapeType SCALAR =
    MatlabArray_ShapeType_SCALAR;
  static inline bool ShapeType_IsValid(int value) {
    return MatlabArray_ShapeType_IsValid(value);
  }
  static const ShapeType ShapeType_MIN =
    MatlabArray_ShapeType_ShapeType_MIN;
  static const ShapeType ShapeType_MAX =
    MatlabArray_ShapeType_ShapeType_MAX;
  static const int ShapeType_ARRAYSIZE =
    MatlabArray_ShapeType_ShapeType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ShapeType_descriptor() {
    return MatlabArray_ShapeType_descriptor();
  }
  static inline const ::std::string& ShapeType_Name(ShapeType value) {
    return MatlabArray_ShapeType_Name(value);
  }
  static inline bool ShapeType_Parse(const ::std::string& name,
      ShapeType* value) {
    return MatlabArray_ShapeType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional bytes data = 4;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 4;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // optional .drake.common.MatlabArray.ArrayType type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::drake::common::MatlabArray_ArrayType type() const;
  void set_type(::drake::common::MatlabArray_ArrayType value);

  // optional int32 rows = 2;
  bool has_rows() const;
  void clear_rows();
  static const int kRowsFieldNumber = 2;
  ::google::protobuf::int32 rows() const;
  void set_rows(::google::protobuf::int32 value);

  // optional int32 cols = 3;
  bool has_cols() const;
  void clear_cols();
  static const int kColsFieldNumber = 3;
  ::google::protobuf::int32 cols() const;
  void set_cols(::google::protobuf::int32 value);

  // optional .drake.common.MatlabArray.ShapeType shape_type = 5;
  bool has_shape_type() const;
  void clear_shape_type();
  static const int kShapeTypeFieldNumber = 5;
  ::drake::common::MatlabArray_ShapeType shape_type() const;
  void set_shape_type(::drake::common::MatlabArray_ShapeType value);

  // @@protoc_insertion_point(class_scope:drake.common.MatlabArray)
 private:
  void set_has_type();
  void clear_has_type();
  void set_has_rows();
  void clear_has_rows();
  void set_has_cols();
  void clear_has_cols();
  void set_has_shape_type();
  void clear_has_shape_type();
  void set_has_data();
  void clear_has_data();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  int type_;
  ::google::protobuf::int32 rows_;
  ::google::protobuf::int32 cols_;
  int shape_type_;
  friend struct ::protobuf_drake_2fcommon_2fproto_2fmatlab_5frpc_2eproto::TableStruct;
  friend void ::protobuf_drake_2fcommon_2fproto_2fmatlab_5frpc_2eproto::InitDefaultsMatlabArrayImpl();
};
// -------------------------------------------------------------------

class MatlabRPC : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:drake.common.MatlabRPC) */ {
 public:
  MatlabRPC();
  virtual ~MatlabRPC();

  MatlabRPC(const MatlabRPC& from);

  inline MatlabRPC& operator=(const MatlabRPC& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MatlabRPC(MatlabRPC&& from) noexcept
    : MatlabRPC() {
    *this = ::std::move(from);
  }

  inline MatlabRPC& operator=(MatlabRPC&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MatlabRPC& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MatlabRPC* internal_default_instance() {
    return reinterpret_cast<const MatlabRPC*>(
               &_MatlabRPC_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(MatlabRPC* other);
  friend void swap(MatlabRPC& a, MatlabRPC& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MatlabRPC* New() const PROTOBUF_FINAL { return New(NULL); }

  MatlabRPC* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MatlabRPC& from);
  void MergeFrom(const MatlabRPC& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MatlabRPC* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 lhs = 1;
  int lhs_size() const;
  void clear_lhs();
  static const int kLhsFieldNumber = 1;
  ::google::protobuf::int64 lhs(int index) const;
  void set_lhs(int index, ::google::protobuf::int64 value);
  void add_lhs(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      lhs() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_lhs();

  // repeated .drake.common.MatlabArray rhs = 2;
  int rhs_size() const;
  void clear_rhs();
  static const int kRhsFieldNumber = 2;
  const ::drake::common::MatlabArray& rhs(int index) const;
  ::drake::common::MatlabArray* mutable_rhs(int index);
  ::drake::common::MatlabArray* add_rhs();
  ::google::protobuf::RepeatedPtrField< ::drake::common::MatlabArray >*
      mutable_rhs();
  const ::google::protobuf::RepeatedPtrField< ::drake::common::MatlabArray >&
      rhs() const;

  // optional string function_name = 3;
  bool has_function_name() const;
  void clear_function_name();
  static const int kFunctionNameFieldNumber = 3;
  const ::std::string& function_name() const;
  void set_function_name(const ::std::string& value);
  #if LANG_CXX11
  void set_function_name(::std::string&& value);
  #endif
  void set_function_name(const char* value);
  void set_function_name(const char* value, size_t size);
  ::std::string* mutable_function_name();
  ::std::string* release_function_name();
  void set_allocated_function_name(::std::string* function_name);

  // @@protoc_insertion_point(class_scope:drake.common.MatlabRPC)
 private:
  void set_has_function_name();
  void clear_has_function_name();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > lhs_;
  ::google::protobuf::RepeatedPtrField< ::drake::common::MatlabArray > rhs_;
  ::google::protobuf::internal::ArenaStringPtr function_name_;
  friend struct ::protobuf_drake_2fcommon_2fproto_2fmatlab_5frpc_2eproto::TableStruct;
  friend void ::protobuf_drake_2fcommon_2fproto_2fmatlab_5frpc_2eproto::InitDefaultsMatlabRPCImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MatlabArray

// optional .drake.common.MatlabArray.ArrayType type = 1;
inline bool MatlabArray::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MatlabArray::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MatlabArray::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MatlabArray::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::drake::common::MatlabArray_ArrayType MatlabArray::type() const {
  // @@protoc_insertion_point(field_get:drake.common.MatlabArray.type)
  return static_cast< ::drake::common::MatlabArray_ArrayType >(type_);
}
inline void MatlabArray::set_type(::drake::common::MatlabArray_ArrayType value) {
  assert(::drake::common::MatlabArray_ArrayType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:drake.common.MatlabArray.type)
}

// optional int32 rows = 2;
inline bool MatlabArray::has_rows() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MatlabArray::set_has_rows() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MatlabArray::clear_has_rows() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MatlabArray::clear_rows() {
  rows_ = 0;
  clear_has_rows();
}
inline ::google::protobuf::int32 MatlabArray::rows() const {
  // @@protoc_insertion_point(field_get:drake.common.MatlabArray.rows)
  return rows_;
}
inline void MatlabArray::set_rows(::google::protobuf::int32 value) {
  set_has_rows();
  rows_ = value;
  // @@protoc_insertion_point(field_set:drake.common.MatlabArray.rows)
}

// optional int32 cols = 3;
inline bool MatlabArray::has_cols() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MatlabArray::set_has_cols() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MatlabArray::clear_has_cols() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MatlabArray::clear_cols() {
  cols_ = 0;
  clear_has_cols();
}
inline ::google::protobuf::int32 MatlabArray::cols() const {
  // @@protoc_insertion_point(field_get:drake.common.MatlabArray.cols)
  return cols_;
}
inline void MatlabArray::set_cols(::google::protobuf::int32 value) {
  set_has_cols();
  cols_ = value;
  // @@protoc_insertion_point(field_set:drake.common.MatlabArray.cols)
}

// optional .drake.common.MatlabArray.ShapeType shape_type = 5;
inline bool MatlabArray::has_shape_type() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MatlabArray::set_has_shape_type() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MatlabArray::clear_has_shape_type() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MatlabArray::clear_shape_type() {
  shape_type_ = 0;
  clear_has_shape_type();
}
inline ::drake::common::MatlabArray_ShapeType MatlabArray::shape_type() const {
  // @@protoc_insertion_point(field_get:drake.common.MatlabArray.shape_type)
  return static_cast< ::drake::common::MatlabArray_ShapeType >(shape_type_);
}
inline void MatlabArray::set_shape_type(::drake::common::MatlabArray_ShapeType value) {
  assert(::drake::common::MatlabArray_ShapeType_IsValid(value));
  set_has_shape_type();
  shape_type_ = value;
  // @@protoc_insertion_point(field_set:drake.common.MatlabArray.shape_type)
}

// optional bytes data = 4;
inline bool MatlabArray::has_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MatlabArray::set_has_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MatlabArray::clear_has_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MatlabArray::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_data();
}
inline const ::std::string& MatlabArray::data() const {
  // @@protoc_insertion_point(field_get:drake.common.MatlabArray.data)
  return data_.GetNoArena();
}
inline void MatlabArray::set_data(const ::std::string& value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:drake.common.MatlabArray.data)
}
#if LANG_CXX11
inline void MatlabArray::set_data(::std::string&& value) {
  set_has_data();
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:drake.common.MatlabArray.data)
}
#endif
inline void MatlabArray::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:drake.common.MatlabArray.data)
}
inline void MatlabArray::set_data(const void* value, size_t size) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:drake.common.MatlabArray.data)
}
inline ::std::string* MatlabArray::mutable_data() {
  set_has_data();
  // @@protoc_insertion_point(field_mutable:drake.common.MatlabArray.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MatlabArray::release_data() {
  // @@protoc_insertion_point(field_release:drake.common.MatlabArray.data)
  clear_has_data();
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MatlabArray::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    set_has_data();
  } else {
    clear_has_data();
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:drake.common.MatlabArray.data)
}

// -------------------------------------------------------------------

// MatlabRPC

// repeated int64 lhs = 1;
inline int MatlabRPC::lhs_size() const {
  return lhs_.size();
}
inline void MatlabRPC::clear_lhs() {
  lhs_.Clear();
}
inline ::google::protobuf::int64 MatlabRPC::lhs(int index) const {
  // @@protoc_insertion_point(field_get:drake.common.MatlabRPC.lhs)
  return lhs_.Get(index);
}
inline void MatlabRPC::set_lhs(int index, ::google::protobuf::int64 value) {
  lhs_.Set(index, value);
  // @@protoc_insertion_point(field_set:drake.common.MatlabRPC.lhs)
}
inline void MatlabRPC::add_lhs(::google::protobuf::int64 value) {
  lhs_.Add(value);
  // @@protoc_insertion_point(field_add:drake.common.MatlabRPC.lhs)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
MatlabRPC::lhs() const {
  // @@protoc_insertion_point(field_list:drake.common.MatlabRPC.lhs)
  return lhs_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
MatlabRPC::mutable_lhs() {
  // @@protoc_insertion_point(field_mutable_list:drake.common.MatlabRPC.lhs)
  return &lhs_;
}

// repeated .drake.common.MatlabArray rhs = 2;
inline int MatlabRPC::rhs_size() const {
  return rhs_.size();
}
inline void MatlabRPC::clear_rhs() {
  rhs_.Clear();
}
inline const ::drake::common::MatlabArray& MatlabRPC::rhs(int index) const {
  // @@protoc_insertion_point(field_get:drake.common.MatlabRPC.rhs)
  return rhs_.Get(index);
}
inline ::drake::common::MatlabArray* MatlabRPC::mutable_rhs(int index) {
  // @@protoc_insertion_point(field_mutable:drake.common.MatlabRPC.rhs)
  return rhs_.Mutable(index);
}
inline ::drake::common::MatlabArray* MatlabRPC::add_rhs() {
  // @@protoc_insertion_point(field_add:drake.common.MatlabRPC.rhs)
  return rhs_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::drake::common::MatlabArray >*
MatlabRPC::mutable_rhs() {
  // @@protoc_insertion_point(field_mutable_list:drake.common.MatlabRPC.rhs)
  return &rhs_;
}
inline const ::google::protobuf::RepeatedPtrField< ::drake::common::MatlabArray >&
MatlabRPC::rhs() const {
  // @@protoc_insertion_point(field_list:drake.common.MatlabRPC.rhs)
  return rhs_;
}

// optional string function_name = 3;
inline bool MatlabRPC::has_function_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MatlabRPC::set_has_function_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MatlabRPC::clear_has_function_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MatlabRPC::clear_function_name() {
  function_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_function_name();
}
inline const ::std::string& MatlabRPC::function_name() const {
  // @@protoc_insertion_point(field_get:drake.common.MatlabRPC.function_name)
  return function_name_.GetNoArena();
}
inline void MatlabRPC::set_function_name(const ::std::string& value) {
  set_has_function_name();
  function_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:drake.common.MatlabRPC.function_name)
}
#if LANG_CXX11
inline void MatlabRPC::set_function_name(::std::string&& value) {
  set_has_function_name();
  function_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:drake.common.MatlabRPC.function_name)
}
#endif
inline void MatlabRPC::set_function_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_function_name();
  function_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:drake.common.MatlabRPC.function_name)
}
inline void MatlabRPC::set_function_name(const char* value, size_t size) {
  set_has_function_name();
  function_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:drake.common.MatlabRPC.function_name)
}
inline ::std::string* MatlabRPC::mutable_function_name() {
  set_has_function_name();
  // @@protoc_insertion_point(field_mutable:drake.common.MatlabRPC.function_name)
  return function_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MatlabRPC::release_function_name() {
  // @@protoc_insertion_point(field_release:drake.common.MatlabRPC.function_name)
  clear_has_function_name();
  return function_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MatlabRPC::set_allocated_function_name(::std::string* function_name) {
  if (function_name != NULL) {
    set_has_function_name();
  } else {
    clear_has_function_name();
  }
  function_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), function_name);
  // @@protoc_insertion_point(field_set_allocated:drake.common.MatlabRPC.function_name)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace common
}  // namespace drake

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::drake::common::MatlabArray_ArrayType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::drake::common::MatlabArray_ArrayType>() {
  return ::drake::common::MatlabArray_ArrayType_descriptor();
}
template <> struct is_proto_enum< ::drake::common::MatlabArray_ShapeType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::drake::common::MatlabArray_ShapeType>() {
  return ::drake::common::MatlabArray_ShapeType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_drake_2fcommon_2fproto_2fmatlab_5frpc_2eproto__INCLUDED
