#pragma once
#include <lcmtypes/bot_core/atlas_command_t.hpp>
#include <lcmtypes/bot_core/double_array_t.hpp>
#include <lcmtypes/bot_core/force_torque_t.hpp>
#include <lcmtypes/bot_core/gps_data_t.hpp>
#include <lcmtypes/bot_core/gps_satellite_info_list_t.hpp>
#include <lcmtypes/bot_core/gps_satellite_info_t.hpp>
#include <lcmtypes/bot_core/image_metadata_t.hpp>
#include <lcmtypes/bot_core/image_sync_t.hpp>
#include <lcmtypes/bot_core/image_t.hpp>
#include <lcmtypes/bot_core/images_t.hpp>
#include <lcmtypes/bot_core/ins_t.hpp>
#include <lcmtypes/bot_core/joint_angles_t.hpp>
#include <lcmtypes/bot_core/joint_state_t.hpp>
#include <lcmtypes/bot_core/kvh_raw_imu_batch_t.hpp>
#include <lcmtypes/bot_core/kvh_raw_imu_t.hpp>
#include <lcmtypes/bot_core/planar_lidar_t.hpp>
#include <lcmtypes/bot_core/pointcloud2_t.hpp>
#include <lcmtypes/bot_core/pointcloud_t.hpp>
#include <lcmtypes/bot_core/pointfield_t.hpp>
#include <lcmtypes/bot_core/pose_t.hpp>
#include <lcmtypes/bot_core/position_3d_t.hpp>
#include <lcmtypes/bot_core/quaternion_t.hpp>
#include <lcmtypes/bot_core/raw_t.hpp>
#include <lcmtypes/bot_core/rigid_transform_t.hpp>
#include <lcmtypes/bot_core/robot_state_t.hpp>
#include <lcmtypes/bot_core/robot_urdf_t.hpp>
#include <lcmtypes/bot_core/sensor_status_t.hpp>
#include <lcmtypes/bot_core/six_axis_force_torque_array_t.hpp>
#include <lcmtypes/bot_core/six_axis_force_torque_t.hpp>
#include <lcmtypes/bot_core/system_status_t.hpp>
#include <lcmtypes/bot_core/twist_t.hpp>
#include <lcmtypes/bot_core/utime_t.hpp>
#include <lcmtypes/bot_core/vector_3d_t.hpp>
#include <lcmtypes/bot_core/viewer_command_t.hpp>
#include <lcmtypes/bot_core/viewer_draw_t.hpp>
#include <lcmtypes/bot_core/viewer_geometry_data_t.hpp>
#include <lcmtypes/bot_core/viewer_link_data_t.hpp>
#include <lcmtypes/bot_core/viewer_load_robot_t.hpp>