#pragma once
#include <lcmtypes/robotlocomotion_grasp_transition_state_t.h>
#include <lcmtypes/robotlocomotion_header_t.h>
#include <lcmtypes/robotlocomotion_image_array_t.h>
#include <lcmtypes/robotlocomotion_image_t.h>
#include <lcmtypes/robotlocomotion_plan_control_t.h>
#include <lcmtypes/robotlocomotion_plan_status_t.h>
#include <lcmtypes/robotlocomotion_point_t.h>
#include <lcmtypes/robotlocomotion_pose_stamped_t.h>
#include <lcmtypes/robotlocomotion_pose_t.h>
#include <lcmtypes/robotlocomotion_quaternion_t.h>
#include <lcmtypes/robotlocomotion_residual_observer_state_t.h>
#include <lcmtypes/robotlocomotion_robot_plan_t.h>
#include <lcmtypes/robotlocomotion_robot_plan_w_keyframes_t.h>
#include <lcmtypes/robotlocomotion_robot_plan_with_supports_t.h>
#include <lcmtypes/robotlocomotion_support_body_t.h>
#include <lcmtypes/robotlocomotion_support_element_t.h>
#include <lcmtypes/robotlocomotion_support_sequence_t.h>
#include <lcmtypes/robotlocomotion_viewer2_comms_t.h>
#include <lcmtypes/robotlocomotion_viewer_command_t.h>
#include <lcmtypes/robotlocomotion_viewer_draw_t.h>
#include <lcmtypes/robotlocomotion_viewer_geometry_data_t.h>
#include <lcmtypes/robotlocomotion_viewer_link_data_t.h>
#include <lcmtypes/robotlocomotion_viewer_load_robot_t.h>