/* Config.hh. Generated by CMake for ignition-rndf. */

/* Version number */
#define IGNITION_RNDF_MAJOR_VERSION 0
#define IGNITION_RNDF_MINOR_VERSION 1
#define IGNITION_RNDF_PATCH_VERSION 5

#define IGNITION_RNDF_VERSION "0.1"
#define IGNITION_RNDF_VERSION_FULL "0.1.5"

#define IGNITION_RNDF_VERSION_HEADER "ignition-rndf, version 0.1.5\nCopyright (C) 2017 Open Source Robotics Foundation.\nReleased under the Apache 2.0 License.\n\n"

#define BUILD_TYPE_PROFILE 1
#define BUILD_TYPE_DEBUG 1
#define BUILD_TYPE_RELEASE 1
