/* Config.hh. Generated by CMake for ignition-math. */

/* Version number */
#define IGNITION_MATH_MAJOR_VERSION 3
#define IGNITION_MATH_MINOR_VERSION 2
#define IGNITION_MATH_PATCH_VERSION 0

#define IGNITION_MATH_VERSION "3.2"
#define IGNITION_MATH_VERSION_FULL "3.2.0"

#define IGNITION_MATH_VERSION_HEADER "Ignition math, version 3.2.0\nCopyright (C) 2014 Open Source Robotics Foundation.\nReleased under the Apache 2.0 License.\n\n"

#define BUILD_TYPE_PROFILE 1
#define BUILD_TYPE_DEBUG 1
#define BUILD_TYPE_RELEASE 1
